-- Update institution stats
UPDATE institutions SET total_students = 6, total_faculty = 15 WHERE aishe_code = 'AISHE002';

-- Add more students (5 more to make 6 total)
INSERT INTO users (email, password_hash, role, full_name, national_id) VALUES
('student2@example.com', 'hashedpass', 'student', 'Alice Johnson', 'STU002'),
('student3@example.com', 'hashedpass', 'student', 'Bob Wilson', 'STU003'),
('student4@example.com', 'hashedpass', 'student', 'Carol Brown', 'STU004'),
('student5@example.com', 'hashedpass', 'student', 'David Lee', 'STU005'),
('student6@example.com', 'hashedpass', 'student', 'Emma Davis', 'STU006');

INSERT INTO students (user_id, aadhar_id, institution_id, enrollment_number, course, year_of_study, cgpa, date_of_birth, gender, category) VALUES
((SELECT id FROM users WHERE email='student2@example.com'), '123456789013', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'ENR002', 'Electrical Engineering', 2, 7.8, '2001-03-15', 'Female', 'General'),
((SELECT id FROM users WHERE email='student3@example.com'), '123456789014', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'ENR003', 'Mechanical Engineering', 4, 8.2, '1999-07-22', 'Male', 'OBC'),
((SELECT id FROM users WHERE email='student4@example.com'), '123456789015', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'ENR004', 'Civil Engineering', 3, 7.5, '2000-11-08', 'Female', 'SC'),
((SELECT id FROM users WHERE email='student5@example.com'), '123456789016', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'ENR005', 'Computer Science', 1, 8.9, '2002-05-30', 'Male', 'General'),
((SELECT id FROM users WHERE email='student6@example.com'), '123456789017', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'ENR006', 'Information Technology', 2, 8.1, '2001-09-12', 'Female', 'General');

-- Add more teachers (14 more to make 15 total)
INSERT INTO users (email, password_hash, role, full_name, national_id) VALUES
('teacher2@example.com', 'hashedpass', 'teacher', 'Dr. Robert Smith', 'TEA002'),
('teacher3@example.com', 'hashedpass', 'teacher', 'Prof. Lisa Anderson', 'TEA003'),
('teacher4@example.com', 'hashedpass', 'teacher', 'Dr. Michael Johnson', 'TEA004'),
('teacher5@example.com', 'hashedpass', 'teacher', 'Prof. Sarah Wilson', 'TEA005'),
('teacher6@example.com', 'hashedpass', 'teacher', 'Dr. James Brown', 'TEA006'),
('teacher7@example.com', 'hashedpass', 'teacher', 'Prof. Emily Davis', 'TEA007'),
('teacher8@example.com', 'hashedpass', 'teacher', 'Dr. David Miller', 'TEA008'),
('teacher9@example.com', 'hashedpass', 'teacher', 'Prof. Jennifer Garcia', 'TEA009'),
('teacher10@example.com', 'hashedpass', 'teacher', 'Dr. Christopher Martinez', 'TEA010'),
('teacher11@example.com', 'hashedpass', 'teacher', 'Prof. Amanda Rodriguez', 'TEA011'),
('teacher12@example.com', 'hashedpass', 'teacher', 'Dr. Daniel Taylor', 'TEA012'),
('teacher13@example.com', 'hashedpass', 'teacher', 'Prof. Jessica Thomas', 'TEA013'),
('teacher14@example.com', 'hashedpass', 'teacher', 'Dr. Matthew Jackson', 'TEA014'),
('teacher15@example.com', 'hashedpass', 'teacher', 'Prof. Ashley White', 'TEA015');

INSERT INTO teachers (user_id, apar_id, institution_id, department, designation, specialization, years_of_experience, research_papers) VALUES
((SELECT id FROM users WHERE email='teacher2@example.com'), 'APAR002', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Electrical Engineering', 'Associate Professor', 'Power Systems', 12, 18),
((SELECT id FROM users WHERE email='teacher3@example.com'), 'APAR003', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Mechanical Engineering', 'Professor', 'Thermodynamics', 18, 32),
((SELECT id FROM users WHERE email='teacher4@example.com'), 'APAR004', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Civil Engineering', 'Assistant Professor', 'Structural Engineering', 8, 12),
((SELECT id FROM users WHERE email='teacher5@example.com'), 'APAR005', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Computer Science', 'Associate Professor', 'Data Science', 10, 22),
((SELECT id FROM users WHERE email='teacher6@example.com'), 'APAR006', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Information Technology', 'Professor', 'Cybersecurity', 20, 45),
((SELECT id FROM users WHERE email='teacher7@example.com'), 'APAR007', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Mathematics', 'Assistant Professor', 'Applied Mathematics', 6, 8),
((SELECT id FROM users WHERE email='teacher8@example.com'), 'APAR008', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Physics', 'Professor', 'Quantum Physics', 22, 38),
((SELECT id FROM users WHERE email='teacher9@example.com'), 'APAR009', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Chemistry', 'Associate Professor', 'Organic Chemistry', 14, 26),
((SELECT id FROM users WHERE email='teacher10@example.com'), 'APAR010', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Biology', 'Assistant Professor', 'Biotechnology', 7, 11),
((SELECT id FROM users WHERE email='teacher11@example.com'), 'APAR011', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'English', 'Professor', 'Literature', 25, 40),
((SELECT id FROM users WHERE email='teacher12@example.com'), 'APAR012', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Economics', 'Associate Professor', 'Macroeconomics', 16, 28),
((SELECT id FROM users WHERE email='teacher13@example.com'), 'APAR013', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'History', 'Assistant Professor', 'Modern History', 9, 15),
((SELECT id FROM users WHERE email='teacher14@example.com'), 'APAR014', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Psychology', 'Professor', 'Clinical Psychology', 19, 35),
((SELECT id FROM users WHERE email='teacher15@example.com'), 'APAR015', (SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Business Administration', 'Associate Professor', 'Marketing', 13, 24);

-- Add scheme beneficiaries to match dashboard numbers
INSERT INTO scheme_beneficiaries (scheme_id, student_id, institution_id, application_date, approval_status, amount_disbursed) VALUES
-- PM-USHA: 2 beneficiaries
((SELECT id FROM schemes WHERE name='PM-USHA'), (SELECT id FROM students WHERE enrollment_number='ENR001'), (SELECT id FROM institutions WHERE aishe_code='AISHE002'), now(), 'approved', 60000),
((SELECT id FROM schemes WHERE name='PM-USHA'), (SELECT id FROM students WHERE enrollment_number='ENR002'), (SELECT id FROM institutions WHERE aishe_code='AISHE002'), now(), 'approved', 60000),

-- RUSA: 1 beneficiary
((SELECT id FROM schemes WHERE name='RUSA'), NULL, (SELECT id FROM institutions WHERE aishe_code='AISHE002'), now(), 'approved', 800000),

-- National Scholarship: 3 beneficiaries
((SELECT id FROM schemes WHERE name='National Scholarship'), (SELECT id FROM students WHERE enrollment_number='ENR003'), (SELECT id FROM institutions WHERE aishe_code='AISHE002'), now(), 'approved', 80000),
((SELECT id FROM schemes WHERE name='National Scholarship'), (SELECT id FROM students WHERE enrollment_number='ENR004'), (SELECT id FROM institutions WHERE aishe_code='AISHE002'), now(), 'approved', 80000),
((SELECT id FROM schemes WHERE name='National Scholarship'), (SELECT id FROM students WHERE enrollment_number='ENR005'), (SELECT id FROM institutions WHERE aishe_code='AISHE002'), now(), 'approved', 80000);

-- Add activities to represent reports generated (100 activities)
INSERT INTO activities (institution_id, title, description, activity_type, status, activity_date) VALUES
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Student Enrollment Report', 'Monthly enrollment statistics', 'report', 'completed', now() - interval '1 day'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Faculty Performance Review', 'Annual faculty evaluation', 'report', 'completed', now() - interval '2 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Infrastructure Audit', 'Campus facilities assessment', 'report', 'completed', now() - interval '3 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Research Publications', 'Monthly research output', 'report', 'completed', now() - interval '4 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Student Attendance Report', 'Weekly attendance summary', 'report', 'completed', now() - interval '5 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Budget Utilization', 'Quarterly budget analysis', 'report', 'completed', now() - interval '6 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Placement Statistics', 'Monthly placement report', 'report', 'completed', now() - interval '7 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Library Usage Report', 'Book circulation statistics', 'report', 'completed', now() - interval '8 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Exam Results Analysis', 'Semester exam performance', 'report', 'completed', now() - interval '9 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Sports Activities Report', 'Annual sports participation', 'report', 'completed', now() - interval '10 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Cultural Events Summary', 'Monthly cultural activities', 'report', 'completed', now() - interval '11 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Alumni Engagement', 'Alumni interaction report', 'report', 'completed', now() - interval '12 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Industry Partnerships', 'Collaboration activities', 'report', 'completed', now() - interval '13 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Digital Learning Stats', 'Online course usage', 'report', 'completed', now() - interval '14 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Student Feedback Analysis', 'Course feedback summary', 'report', 'completed', now() - interval '15 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Research Grants Report', 'Funding acquisition summary', 'report', 'completed', now() - interval '16 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Innovation Hub Activities', 'Startup incubation report', 'report', 'completed', now() - interval '17 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'International Collaborations', 'Global partnership activities', 'report', 'completed', now() - interval '18 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Sustainability Report', 'Green campus initiatives', 'report', 'completed', now() - interval '19 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Mental Health Support', 'Student wellness program', 'report', 'completed', now() - interval '20 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Diversity Inclusion Report', 'Equity and inclusion metrics', 'report', 'completed', now() - interval '21 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Technology Infrastructure', 'IT systems performance', 'report', 'completed', now() - interval '22 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Community Outreach', 'Social responsibility activities', 'report', 'completed', now() - interval '23 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Academic Calendar Review', 'Semester planning report', 'report', 'completed', now() - interval '24 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Quality Assurance', 'Accreditation preparation', 'report', 'completed', now() - interval '25 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Student Exchange Program', 'International student mobility', 'report', 'completed', now() - interval '26 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Continuing Education', 'Professional development', 'report', 'completed', now() - interval '27 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Campus Security Report', 'Safety and security metrics', 'report', 'completed', now() - interval '28 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Financial Aid Distribution', 'Scholarship disbursement', 'report', 'completed', now() - interval '29 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Curriculum Development', 'Course design activities', 'report', 'completed', now() - interval '30 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Student Council Activities', 'Leadership program report', 'report', 'completed', now() - interval '31 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Environmental Impact', 'Carbon footprint analysis', 'report', 'completed', now() - interval '32 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Digital Transformation', 'Technology adoption metrics', 'report', 'completed', now() - interval '33 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Employee Satisfaction', 'Staff feedback analysis', 'report', 'completed', now() - interval '34 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Parent Engagement', 'Family involvement activities', 'report', 'completed', now() - interval '35 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Industry Advisory Board', 'External stakeholder meetings', 'report', 'completed', now() - interval '36 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Graduate Outcomes', 'Alumni success tracking', 'report', 'completed', now() - interval '37 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Teaching Innovation', 'Pedagogical improvements', 'report', 'completed', now() - interval '38 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Student Entrepreneurship', 'Business incubation activities', 'report', 'completed', now() - interval '39 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Accessibility Compliance', 'Disability support services', 'report', 'completed', now() - interval '40 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Research Ethics', 'Ethical research practices', 'report', 'completed', now() - interval '41 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Language Programs', 'Foreign language offerings', 'report', 'completed', now() - interval '42 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Health Services', 'Medical facility utilization', 'report', 'completed', now() - interval '43 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Transportation Services', 'Campus shuttle usage', 'report', 'completed', now() - interval '44 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Food Services', 'Cafeteria and dining stats', 'report', 'completed', now() - interval '45 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Housing Facilities', 'Dormitory occupancy', 'report', 'completed', now() - interval '46 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Recreational Facilities', 'Gym and sports usage', 'report', 'completed', now() - interval '47 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Art and Culture', 'Creative activities report', 'report', 'completed', now() - interval '48 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Music and Performing Arts', 'Arts program activities', 'report', 'completed', now() - interval '49 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Debate and Public Speaking', 'Communication skills training', 'report', 'completed', now() - interval '50 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Volunteer Programs', 'Community service activities', 'report', 'completed', now() - interval '51 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Internship Placements', 'Work experience opportunities', 'report', 'completed', now() - interval '52 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Career Counseling', 'Professional guidance services', 'report', 'completed', now() - interval '53 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Skill Development', 'Workshop and training programs', 'report', 'completed', now() - interval '54 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Leadership Training', 'Management development', 'report', 'completed', now() - interval '55 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Mentorship Program', 'Faculty-student pairing', 'report', 'completed', now() - interval '56 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Peer Learning', 'Student-to-student teaching', 'report', 'completed', now() - interval '57 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Online Learning', 'Digital education platforms', 'report', 'completed', now() - interval '58 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Blended Learning', 'Hybrid teaching methods', 'report', 'completed', now() - interval '59 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Project-Based Learning', 'Hands-on learning activities', 'report', 'completed', now() - interval '60 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Collaborative Learning', 'Group work initiatives', 'report', 'completed', now() - interval '61 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Experiential Learning', 'Real-world application', 'report', 'completed', now() - interval '62 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Field Studies', 'Off-campus learning', 'report', 'completed', now() - interval '63 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Study Abroad', 'International education', 'report', 'completed', now() - interval '64 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Exchange Programs', 'Student mobility', 'report', 'completed', now() - interval '65 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Summer Schools', 'Intensive learning programs', 'report', 'completed', now() - interval '66 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Winter Sessions', 'Additional academic terms', 'report', 'completed', now() - interval '67 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Certificate Programs', 'Short-term qualifications', 'report', 'completed', now() - interval '68 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Diploma Courses', 'Specialized training', 'report', 'completed', now() - interval '69 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Professional Courses', 'Industry-specific training', 'report', 'completed', now() - interval '70 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Executive Education', 'Leadership programs', 'report', 'completed', now() - interval '71 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Lifelong Learning', 'Continuing education', 'report', 'completed', now() - interval '72 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Community Education', 'Public learning programs', 'report', 'completed', now() - interval '73 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Corporate Training', 'Business education', 'report', 'completed', now() - interval '74 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Government Partnerships', 'Public sector collaboration', 'report', 'completed', now() - interval '75 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'NGO Collaborations', 'Non-profit partnerships', 'report', 'completed', now() - interval '76 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Industry-Academia Linkages', 'Business-university ties', 'report', 'completed', now() - interval '77 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Technology Transfer', 'Innovation commercialization', 'report', 'completed', now() - interval '78 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Patent Filings', 'Intellectual property', 'report', 'completed', now() - interval '79 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Startup Incubation', 'Entrepreneurship support', 'report', 'completed', now() - interval '80 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Technology Licensing', 'IP commercialization', 'report', 'completed', now() - interval '81 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Consulting Services', 'Expert advisory', 'report', 'completed', now() - interval '82 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Knowledge Transfer', 'Technology dissemination', 'report', 'completed', now() - interval '83 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Policy Research', 'Government advisory', 'report', 'completed', now() - interval '84 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Social Impact Studies', 'Community research', 'report', 'completed', now() - interval '85 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Economic Development', 'Regional growth studies', 'report', 'completed', now() - interval '86 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Environmental Research', 'Sustainability studies', 'report', 'completed', now() - interval '87 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Health Research', 'Medical studies', 'report', 'completed', now() - interval '88 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Agricultural Research', 'Food security studies', 'report', 'completed', now() - interval '89 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Engineering Research', 'Technical innovation', 'report', 'completed', now() - interval '90 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Social Sciences', 'Human behavior studies', 'report', 'completed', now() - interval '91 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Humanities Research', 'Cultural studies', 'report', 'completed', now() - interval '92 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Interdisciplinary Studies', 'Cross-disciplinary research', 'report', 'completed', now() - interval '93 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Basic Research', 'Fundamental science', 'report', 'completed', now() - interval '94 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Applied Research', 'Practical applications', 'report', 'completed', now() - interval '95 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Translational Research', 'Lab to market', 'report', 'completed', now() - interval '96 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Clinical Research', 'Medical trials', 'report', 'completed', now() - interval '97 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Field Research', 'Real-world studies', 'report', 'completed', now() - interval '98 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Survey Research', 'Data collection', 'report', 'completed', now() - interval '99 days'),
((SELECT id FROM institutions WHERE aishe_code='AISHE002'), 'Case Study Research', 'In-depth analysis', 'report', 'completed', now() - interval '100 days');
